[package]
name = "coin"
version = "0.1.0"
authors = ["Francisco Calder√≥n <fjcalderon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-hasher = "2.2.1"
